-- Même schéma que l'ancienne base Symfony (SQLite), pour pouvoir reprendre ses données.
CREATE TABLE membre (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, nom VARCHAR(100) NOT NULL);
CREATE UNIQUE INDEX UNIQ_F6B4FB296C6E55B5 ON membre (nom);

CREATE TABLE absence (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, debut DATE NOT NULL, fin DATE NOT NULL, membre_id INTEGER NOT NULL, CONSTRAINT FK_765AE0C96A99F74A FOREIGN KEY (membre_id) REFERENCES membre (id) ON DELETE CASCADE);
CREATE INDEX IDX_765AE0C96A99F74A ON absence (membre_id);

-- poids : JSON { membreId: poids } pour les catégories fixes.
CREATE TABLE categorie (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, nom VARCHAR(100) NOT NULL, type VARCHAR(255) NOT NULL, poids CLOB NOT NULL);

-- montant en centimes.
CREATE TABLE depense (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, libelle VARCHAR(255) NOT NULL, montant INTEGER NOT NULL, date DATE NOT NULL, payeur_id INTEGER NOT NULL, categorie_id INTEGER NOT NULL, CONSTRAINT FK_34059757422667C5 FOREIGN KEY (payeur_id) REFERENCES membre (id), CONSTRAINT FK_34059757BCF5E72D FOREIGN KEY (categorie_id) REFERENCES categorie (id));
CREATE INDEX IDX_34059757422667C5 ON depense (payeur_id);
CREATE INDEX IDX_34059757BCF5E72D ON depense (categorie_id);

-- Participants d'une dépense ; aucun = tout le monde.
CREATE TABLE depense_membre (depense_id INTEGER NOT NULL, membre_id INTEGER NOT NULL, PRIMARY KEY (depense_id, membre_id), CONSTRAINT FK_5E3F0DEE41D81563 FOREIGN KEY (depense_id) REFERENCES depense (id) ON DELETE CASCADE, CONSTRAINT FK_5E3F0DEE6A99F74A FOREIGN KEY (membre_id) REFERENCES membre (id) ON DELETE CASCADE);
CREATE INDEX IDX_5E3F0DEE41D81563 ON depense_membre (depense_id);
CREATE INDEX IDX_5E3F0DEE6A99F74A ON depense_membre (membre_id);

-- Virement fait pour solder un mois (AAAA-MM), montant en centimes.
CREATE TABLE remboursement (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, montant INTEGER NOT NULL, mois VARCHAR(7) NOT NULL, de_id INTEGER NOT NULL, a_id INTEGER NOT NULL, CONSTRAINT FK_C0C0D9EF3F683D83 FOREIGN KEY (de_id) REFERENCES membre (id), CONSTRAINT FK_C0C0D9EF3BDE5358 FOREIGN KEY (a_id) REFERENCES membre (id));
CREATE INDEX IDX_C0C0D9EF3F683D83 ON remboursement (de_id);
CREATE INDEX IDX_C0C0D9EF3BDE5358 ON remboursement (a_id);
